# This is a basic workflow to help you get started with Actions

name: release-pr

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  release:
    branch: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  update-notes:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout
        uses: actions/checkout@v2
      - name: create-pr
        uses: paygoc6/action-pull-request-another-repo@v1.0.1
        env:
          API_TOKEN_GITHUB: ${{secrets.API_TOKEN_GITHUB}}
        with:
          source_folder: 'website_docs/*'
          destination_repo: 'austinlparker/release-pr-target'
          destination_folder: 'content/en/docs/java'
          destination_head_branch: "docs-$GITHUB_REPOSITORY-$GITHUB_SHA"
          user_email: 'austin@lightstep.com'
          user_name: 'austinlparker'
          
